### ISSUE TITLE
4.05.0-ready release?

### ISSUE THREAD

**Issue by gasche** [ocaml-ppx/ppx_tools#59]
I just started looking at the [opam-builder reports for 4.05.0+beta2](http://opam.ocamlpro.com/builder/html/report-full.html), and the fact that no 4.05-ready release of ppx_tools exists is blocking a *lot* of packages. This is a testament to the usefulness of the package, of course, but it would be very nice if we could get a 4.05.0-ready release very soon, to evaluate the *remaining* transition hurdles for the part of the ecosystem that depends on it.

**Comment by mroch** [comment]
looks like 5.0+4.05.0 happened on Feb 26

**Comment by alainfrisch** [comment]
Indeed!
