### ISSUE TITLE
proper release for 5.0

### ISSUE THREAD

**Issue by samoht** [ocaml-ppx/ppx_tools#61]
`ppx_tools.5.0` upstream url is pointing to a non-stable GitHub url:

```
$ opam info ppx_tools.5.0 -f upstream-url
https://github.com/ocaml-ppx/ppx_tools/tarball/f70ca1d07d565989a0041e312e8efc00ff2ad87e
```

that archive is re-generated by GitHub regularly so its md5 is regularly changing. Would it be possible to use a proper release instead? The [current 5.0 release](https://github.com/ocaml-ppx/ppx_tools/releases/tag/5.0) doesn't point to the same SHA1 (not sure why) but it could be nice if it would -- it's seem that GitHub cache for release tarball is much more long-lived in practice (we don't see many md5 changes). It is probably better to upload an archive to that release to be sure that the md5 will never change anymore. `topkg publish` could help to do this automatically.

**Comment by dansanabria** [comment]
is this why I keep getting this when doing `opam install ppx_tools` :
```
=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] Bad checksum for /home/opam/.opam/packages.dev/ppx_tools.5.0/f70ca1d07d565989a0041e312e8efc00ff2ad87e:
          - 1e18ffaa90d51cba9e6d5eb7bd186637 [expected result]
          - 5e1a86ff323fe772d69ca2d25abc2c9d [actual result]
        This may be fixed by running `opam update`.

[ERROR] The sources of the following couldn't be obtained, aborting:
          - ppx_tools.5.0
        (This may be fixed by running 'opam update')
opam@5aee1b375028:~$

`

**Comment by dansanabria** [comment]
Please update my previous comment. Pulling the latest docker image have fixed the error above.

**Comment by XVilka** [comment]
Can be closed now, I believe?

**Comment by samoht** [comment]
Thanks for the reminder :-)
