### ISSUE TITLE
Point opam at the version that supports 4.08.0

### ISSUE THREAD

**Issue by imeckler** [ocaml-ppx/ppx_tools#73]
Currently the version on opam does not work with 4.08.0. I believe a tag needs to be created.

**Comment by XVilka** [comment]
It makes sense to merge https://github.com/ocaml-ppx/ppx_tools/pull/72 before, to avoid the warning.

**Comment by XVilka** [comment]
Can be closed I guess? See https://github.com/ocaml-ppx/ppx_tools/releases/tag/5.2%2B4.08.0

**Comment by kit-ty-kate** [comment]
Indeed. Thanks!
