### ISSUE TITLE
ocaml 5.x support

### ISSUE THREAD

**Issue by cdaringe** [ocaml-ppx/ppx_tools#91]
# problem

i'm trying out ocaml 5, but ppx_tools is not yet compatible

# discussion

no discussion, really. just a tracking thread :)

**Comment by kit-ty-kate** [comment]
That'll be done at some point before the release but I'm surprised to see people are still using ppx_tools.
Is that an internal project? I thought all open source projects had already been ported to ppxlib

**Comment by cdaringe** [comment]
i'm often behind the bandwagon, as i don't work in ocaml regularly :) i'll see if i can port my ppx to use ppxlib
